# Generated by Django 5.0.1 on 2024-01-05 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('Cinema_ID', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('Schedule_ID', models.AutoField(primary_key=True, serialize=False)),
                ('hall_id', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('Seat_ID', models.AutoField(primary_key=True, serialize=False)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall')),
            ],
        ),
    ]
