# Generated by Django 5.0.1 on 2024-01-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_cinema_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
