# Generated by Django 5.0.3 on 2024-05-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_seat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='rating',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
