# Generated by Django 5.0.1 on 2024-01-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
