# Generated by Django 5.0.3 on 2024-05-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
