# Generated by Django 5.0.1 on 2024-01-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_hall_cinema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
