# Generated by Django 5.0.1 on 2024-01-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_ticket_seat_ticket_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
