# Generated by Django 5.0.1 on 2024-01-05 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_profile_user_name'),
        ('cinema', '0002_alter_hall_cinema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('Ticket_ID', models.AutoField(primary_key=True, serialize=False)),
                ('time_on_reserve', models.DateTimeField(auto_now_add=True)),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.seat')),
            ],
        ),
    ]
